name: Continuous Release

on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: verify using node v${{ matrix.node }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm ci
      - run: npm run verify
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: coverage (node v${{ matrix.node }})
          path: coverage/

  publish-npm:
    needs: verify
    runs-on: ubuntu-latest
    name: publish package if needed
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  build-www:
    needs: verify
    runs-on: ubuntu-latest
    name: build website
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist-www
          path: dist/www
          retention-days: 15

  deploy-www:
    needs: build-www
    name: deploy website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist-www
          path: www
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::865116139480:role/github-actions-limulus-penumbra
          aws-region: us-west-2
      - run: aws s3 sync www s3://limulus-net-penumbra --delete --cache-control max-age=60,public
